version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pg-economizza
    environment:
      POSTGRES_DB: economizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - economizza-network

  api:
    build: .
    container_name: economizza-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/economizza
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - economizza-network

volumes:
  postgres_data:

networks:
  economizza-network:
    driver: bridge